# AI知识问答系统 - Docker Compose部署配置
# 包含前端静态页面和后端Spring Boot服务

version: '3.8'

services:
  # 后端服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ai-rag-backend
    restart: unless-stopped
    ports:
      - "8087:8087"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-Djasypt.encryptor.password=lijiaqiang1024@wt1314520
    networks:
      - ai-rag-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # 前端服务
  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: ai-rag-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - ai-rag-network
    # 不再依赖后端服务，使用外部API
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"


# 网络定义
networks:
  ai-rag-network:
    driver: bridge