global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'system-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'system-app:8091'
        labels:
          app: 'system-app'
